"""add_teams

Revision ID: 0cf126545957
Revises: 4c5834afcebf
Create Date: 2021-04-22 21:21:08.660310

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cf126545957'
down_revision = '4c5834afcebf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mp_id', sa.Integer(), nullable=False),
    sa.Column('team_tag1', sa.String(length=3), nullable=True),
    sa.Column('team_tag2', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['mp_id'], ['mp.id'], ),
    sa.PrimaryKeyConstraint('id', 'mp_id')
    )
    op.add_column('mp', sa.Column('teams_setting', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mp', 'teams_setting')
    op.drop_table('team')
    # ### end Alembic commands ###
