"""parse_flag_0

Revision ID: 32741d581dff
Revises: 
Create Date: 2021-02-15 13:13:52.781554

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32741d581dff'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('savegame', sa.Column('parse_flag0', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('savegame', 'parse_flag0')
    # ### end Alembic commands ###
