"""empty message

Revision ID: 4c5834afcebf
Revises: d0ac85e0853b
Create Date: 2021-03-05 23:59:06.544504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5834afcebf'
down_revision = 'd0ac85e0853b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('war_attacker',
    sa.Column('war_id', sa.Integer(), nullable=True),
    sa.Column('attacker_tag', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['attacker_tag'], ['nation.tag'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], )
    )
    op.create_table('war_defender',
    sa.Column('war_id', sa.Integer(), nullable=True),
    sa.Column('defender_tag', sa.String(length=3), nullable=True),
    sa.ForeignKeyConstraint(['defender_tag'], ['nation.tag'], ),
    sa.ForeignKeyConstraint(['war_id'], ['war.id'], )
    )
    op.add_column('mp', sa.Column('institutions', sa.Boolean(), nullable=True))
    op.add_column('mp', sa.Column('victory_points', sa.Boolean(), nullable=True))
    with op.batch_alter_table('war') as batch_op:
        batch_op.drop_column('defender')
        batch_op.drop_column('attacker')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('war', sa.Column('attacker', sa.VARCHAR(length=3), nullable=True))
    op.add_column('war', sa.Column('defender', sa.VARCHAR(length=3), nullable=True))
    with op.batch_alter_table('mp') as batch_op:
        batch_op.drop_column('victory_points')
        batch_op.drop_column('institutions')
    op.drop_table('war_defender')
    op.drop_table('war_attacker')
    # ### end Alembic commands ###
