"""MP-Map

Revision ID: e3e33685bc83
Revises: ccbc7f3e5920
Create Date: 2021-04-24 12:49:34.799822

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3e33685bc83'
down_revision = 'ccbc7f3e5920'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mp', sa.Column('map_file', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mp', 'map_file')
    # ### end Alembic commands ###
